spring.application.name=${SPRING_APPLICATION_NAME:blog}

# JWT
jwt.secret=${JWT_SECRET}
security.jwt.expires-in=${SECURITY_JWT_EXPIRES_IN:86400}

# Default profile can be overridden by env var
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}